// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: okd
:page-layout: guide-multipane
:page-duration: 45 minutes
:page-releasedate: 2019-09-11
:page-description: Explore how to deploy microservices on an OKD cluster using a VM with Minishift. 
:page-tags: ['Kubernetes', 'Docker', 'Cloud'] 
:page-permalink: /guides/{projectid}
:page-related-guides: ['cloud-openshift', 'kubernetes-intro', 'kubernetes-microprofile-config', 'kubernetes-microprofile-health', 'istio-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Deploying microservices on an OKD cluster using Minishift
:page-seo-description: A tutorial on how to deploy microservices using a VM with Minishift. 
:guide-author: Open Liberty
= Deploying microservices on an OKD cluster using Minishift

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].

Explore how to deploy microservices on a OKD 3.x cluster using a VM with Minishift. 

// *********************************************************************************************

//TODO What you'll learn
== What you'll learn 

You will learn how to quickly deploy a Red Hat OKD 3.x cluster on an all-in-one virtual machine (VM) with Minishift. Then, you will deploy two simple REST microservices on an Open Liberty container to the running cluster.

OKD, formerly known as OpenShift Origin, is the upsteam open-source project that powers all OpenShift products. OKD is a Kubernetes-based platform with added functionality. It streamlines the DevOps process by providing an intuitive development pipeline. It also provides integration with multiple tools to make the deployment and management of cloud applications easier. To learn more about the different platforms that Red Hat OpenShift offers, check out their https://docs.openshift.com[official documentation^]. To learn how to deploy microservices to OpenShift Online, check out the https://openliberty.io/guides/cloud-openshift.html[Deploying microservices to OpenShift] guide.

Kubernetes is an open source container orchestrator that automates many tasks that are involved in deploying, managing, and scaling containerized applications. If you would like to learn more about Kubernetes, check out the https://openliberty.io/guides/kubernetes-intro.html[Deploying microservices to Kubernetes^] guide.

Using Maven, you will build a simple microservice, called `system`, that collects basic system properties from your system and displays them on an endpoint that you can access in your web browser. Then, you will build another microservice, `inventory` that will interact with the `system` microservice, and learn how to deploy both to the cluster and establish communication between them.

To do this, you will use Minishift, an all-in-one VM based on Minikube. Similar to how Minikube makes it easy to deploy a local Kubernetes cluster locally, Minishift allows a quick and easy environment for application development that supports all OKD features.

// *********************************************************************************************

//TODO Additional Prerequisites
== Additional Prerequisites 

- *Minishift:* Minishift allows you to easily try OKD by running a VM with a single-node cluster. You can use Minishift with any OS, making it a convenient and flexible tool for testing and development. For installation instructions, refer to the official https://docs.okd.io/latest/minishift/index.html[OKD Minishift documentation].

To verify that Minishift is installed correctly, run the following command:

[role=command]
```
minishift version
```

The output will be similar to:

[role="no_copy"]
----
minishift v1.34.1+c2ff9cb
----

- *Docker:* Docker is a containerization software for building the containers that you will eventually deploy onto the OKD cluster. For installation instructions, refer to the official https://docs.docker.com/install/[Docker documentation^]. To learn how to use Docker for iterative development with Open Liberty, check out the https://openliberty.io/guides/docker.html[Using Docker containers to develop microservices] and the https://openliberty.io/guides/containerize.html[Containerizing microservices] guides.

// *********************************************************************************************

//TODO Getting Started
//== Getting Started

[role=command]
include::{common-includes}/gitclone.adoc[]

// *********************************************************************************************

//TODO Starting Minishift
== Starting Minishift

=== Starting the cluster

Ensure you have Docker installed on your machine, then run the following command to start Minishift:

[role=command]
```
minishift start
```

=== Logging in to the cluster

If the cluster started successfully, the command will output something similar to the following:

[role="no_copy"]
----
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.103:8443/console
----

You can run through the development cycle using OpenShift's intuitive web console through the URL provided in the command output of the `minishift start` command. The web console provides a user friendly GUI alternative to their CLI tools, however this guide will continue with the CLI tools. You can also run the following command to display the URL or open the web console:

[role=command]
```
minishift console
```

Log in with the following credentials:

[role="no_copy"]
----
User:     developer
Password: [any value]
----

You can confirm your credentials by running the `oc whoami` command, and you should get `developer` as your output.

Next, create a new OpenShift project with the following command:

[role=command]
```
oc new-project [project-name]
```

You are now ready to build and deploy a microservice.

// *********************************************************************************************

//TODO Deploying a single microservice
== Deploying a single microservice

//file 0
pom.xml
[source, xml, linenums, role="code_column"]
----
include::hotspots/pom.xml[]
----

//file 1
Dockerfile
[source, Text, linenums, role="code_column"]
----
include::hotspots/Dockerfile[]
----

First, a simple microservice named `system` will be packaged, containerized, and deployed onto the OKD cluster. The `system` microservice will collect the JVM properties of the host machine that accessed the web server, and will output the properties in a JSON format.

=== Building the microservice

First, navigate to the `start` directory, where you will find the source code of the `system` microservice. Also included is the parent Maven Project Object Model (POM) file, the [hotspot file=0]`pom.xml`. To learn more about how to use Maven with Open Liberty, check out the https://openliberty.io/guides/maven-intro.html[Building a web application with Maven] guide. 

In the `start` directory, run the following command to package the application:

[role=command]
```
mvn package
```

The `mvn package` command will compile, verify, and build the project. The resulting compiled code will be packaged into a `tar.gz` archive which can be found at `system/target/system.tar.gz`. The archive contains all the configuration files, as well as the application needed to run the microservice on an Open Liberty server, and is now ready to be injected into a Docker container for deployment.

=== Containerizing the microservice

==== Creating the Dockerfile

Containerizing microservices is a great way to deploy microservices easily, by creating portable containers that can run in any environment. To learn more about containerization, check out the https://openliberty.io/guides/docker.html[Using Docker containers to develop microservices] and the https://openliberty.io/guides/containerize.html[Containerizing microservices] guides. 

To containerize the `system` microservice, it must first be built into a Docker image. To do so, a Dockerfile is needed, to provide instructions to Docker on how to assemble the image. 

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `Dockerfile`.#
`system/Dockerfile`
----

The [hotspot=from file=1]`FROM` instruction initializes a new build stage, which indicates the parent image of the built image. In this case, you’re using the open-liberty image as your parent image, which comes with the Open Liberty runtime by default. You can find all official images at https://hub.docker.com/_/open-liberty[open-liberty Docker Hub].

Use a single [hotspot=add file=1]`ADD` command instead of using multiple `COPY` commands to transfer configuration files and the application because the application is packaged into an archive. It eliminates multiple layers as the Docker image is created, and also convieniently extracts the content of the `system.tar.gz` archive and places it inside the `/opt/ol` directory within the image.

//TODO Continue this sentence with a short explanation as to why.
Finally, the [hotspot=run file=1]`RUN` command is used to change the user and group ownership of the newly extracted directory. 

==== Re-using the Docker daemon

To speed up the development process, we can reuse the built-in Minishift Docker daemon to avoid needing to build a Docker registry on the the host machine. To do this, run the following command:

[role=command]
```
minishift docker-env
```

The result of the command is a list of bash environment variable exports that will configure your environment to re-use the Docker daemon inside the single Minishift VM instance. The commands differe based on your OS and environment, but you will get an output similar to the following:

[role=no_copy]
----
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.103:2376"
export DOCKER_CERT_PATH="/Users/maihameed@ibm.com/.minishift/certs"
# Run this command to configure your shell:
# eval $(minishift docker-env)
----

Run the given `eval` command to configure your environment:

[role=command]
```
eval $(minishift docker-env)
```

==== Building the Docker image

Now that the environment is set up, ensure that you are in the `start` directory and run the following command to build a Docker image according to the instructions in the newly created [file=1]`Dockerfile`:

[role=command]
```
docker build -t system system/
```

The command builds an image named `system` from the [file=1]`Dockerfile` found in the `system` directory. To verify that the images are built, run the following command to list all local Docker images:

[role=command]
```
docker images
```

Your `system` image should appear in the list of all Docker images:

[role=no_copy]
----
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
system                 latest              e8a8393e9364        2 minutes ago       399MB
----

==== Accessing the internal registry

In order to run the microservice on the OKD cluster, you need to push the microservice image into a container image registry. You will use OpenShift’s integrated container image registry called OpenShift Container Registry (OCR). First, you must authenticate your Docker client to your OCR. Start by running the login command:

[role=command]
```
docker login -u `oc whoami` -p `oc whoami -t` `oc registry info`
```

Now you must tag and push your `system` microservice to the internal registry so that it is accessible for deployment. Run the following command to tag your microservice:

[role=command]
```
docker tag system `oc registry info`/`oc project -q`/system
```

Your newly tagged image should appear in the list of all Docker images:

[role=no_copy]
----
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
system                                 latest              e8a8393e9364        2 minutes ago       399MB
172.30.1.1:5000/my-project/system      latest              e8a8393e9364        2 minutes ago       399MB
----

Now push your newly tagged image to the internal registry with the following command:

[role=command]
```
docker push `oc registry info`/`oc project -q`/system
```

Run the following command to view the image stream:

[role=command]
```
oc get imagestream
```

You should find your newly pushed image:

[role=no_copy]
----
NAME      DOCKER REPO                  TAGS      UPDATED
system    172.30.1.1:5000/okd/system   latest    15 hours ago
----

The OpenShift image stream displays all the Docker-formatted container images pushed to the internal registry. You can configure builds and deployments to trigger when an image is updated. The microservice is now ready for deployment.