// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: okd
:page-layout: guide-multipane
:page-duration: 45 minutes
:page-releasedate: 2019-09-11
:page-description: Explore how to deploy microservices on an OKD cluster using a VM with Minishift. 
:page-tags: ['Kubernetes', 'Docker', 'Cloud'] 
:page-permalink: /guides/{projectid}
:page-related-guides: ['cloud-openshift', 'kubernetes-intro', 'kubernetes-microprofile-config', 'kubernetes-microprofile-health', 'istio-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Deploying microservices on an OKD cluster using Minishift
:page-seo-description: A tutorial on how to deploy microservices using a VM with Minishift. 
:guide-author: Open Liberty
= Deploying microservices on an OKD cluster using Minishift

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].

Explore how to deploy microservices on a OKD 3.x cluster using a VM with Minishift. 

// *********************************************************************************************

//TODO What you'll learn
== What you'll learn 

You will learn how to quickly deploy a Red Hat OKD 3.x cluster on an all-in-one virtual machine (VM) with Minishift. Then, you will deploy two simple REST microservices on an Open Liberty container to the running cluster.

OKD, formerly known as OpenShift Origin, is the upsteam open-source project that powers all OpenShift products. OKD is a Kubernetes-based platform with added functionality. It streamlines the DevOps process by providing an intuitive development pipeline. It also provides integration with multiple tools to make the deployment and management of cloud applications easier. To learn more about the different platforms that Red Hat OpenShift offers, check out their https://docs.openshift.com[official documentation^]. To learn how to deploy microservices to OpenShift Online, check out the https://openliberty.io/guides/cloud-openshift.html[Deploying microservices to OpenShift] guide.

Kubernetes is an open source container orchestrator that automates many tasks that are involved in deploying, managing, and scaling containerized applications. If you would like to learn more about Kubernetes, check out the https://openliberty.io/guides/kubernetes-intro.html[Deploying microservices to Kubernetes^] guide.

Using Maven, you will build a simple microservice, called `system`, that collects basic system properties from your system and displays them on an endpoint that you can access in your web browser. Then, you will build another microservice, `inventory` that will interact with the `system` microservice, and learn how to deploy both to the cluster and establish communication between them.

To do this, you will use Minishift, an all-in-one VM based on Minikube. Similar to how Minikube makes it easy to deploy a local Kubernetes cluster locally, Minishift allows a quick and easy environment for application development that supports all OKD features.

// *********************************************************************************************

//TODO Additional Prerequisites
== Additional Prerequisites 

- *Minishift:* Minishift allows you to easily try OKD by running a VM with a single-node cluster. You can use Minishift with any OS, making it a convenient and flexible tool for testing and development. For installation instructions, refer to the official https://docs.okd.io/latest/minishift/index.html[OKD Minishift documentation].

To verify that Minishift is installed correctly, run the following command:

[role=command]
```
minishift version
```

The output will be similar to:

[role="no_copy"]
----
minishift v1.34.1+c2ff9cb
----

- *Docker:* Docker is a containerization software for building the containers that you will eventually deploy onto the OKD cluster. For installation instructions, refer to the official https://docs.docker.com/install/[Docker documentation^]. To learn how to use Docker for iterative development with Open Liberty, check out the https://openliberty.io/guides/docker.html[Using Docker containers to develop microservices] and the https://openliberty.io/guides/containerize.html[Containerizing microservices] guides.

// *********************************************************************************************

//TODO Getting Started
//== Getting Started

[role=command]
include::{common-includes}/gitclone.adoc[]

// *********************************************************************************************

//TODO Accessing the OKD cluster
== Starting Minishift

=== Starting the cluster

Ensure you have Docker installed on your machine, then run the following command to start Minishift:

[role=command]
```
minishift start
```

=== Logging in to the cluster

If the cluster started successfully, the command will output something similar to the following:

[role="no_copy"]
----
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.103:8443/console
----

You can run through the development cycle using OpenShift's intuitive web console through the URL provided in the command output of the `minishift start` command. The web console provides a user friendly GUI alternative to their CLI tools, however this guide will continue with the CLI tools. You can also run the following command to display the URL or open the web console:

[role=command]
```
minishift console
```

Log in with the following credentials:

[role="no_copy"]
----
User:     developer
Password: [any value]
----

You can confirm your credentials by running the `oc whoami` command, and you should get `developer` as your output.

// *********************************************************************************************

//TODO Deploying a single microservice
== Deploying a single microservice

First, a simple microservice named `system` will be packaged, containerized, and deployed onto the OKD cluster. The `system` microservice will collect the JVM properties of the host machine that accessed the web server, and will output the properties in a JSON format.

=== Building the microservice

First, navigate to the `start` directory, where you will find the source code of the `system` microservice inside the `src` directory. 