// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: cloud-openshift //FIX When given repo
:page-layout: guide-multipane
:page-duration: 45 minutes //FIX At end of guide draft
:page-releasedate: 2019-09-11 //FIX At release
:page-description: Explore how to deploy microservices on an OKD cluster hosted on-premises. 
:page-tags: ['Kubernetes', 'Docker', 'Cloud'] 
:page-permalink: /guides/{projectid}
:page-related-guides: ['cloud-openshift', 'kubernetes-intro', 'kubernetes-microprofile-config', 'kubernetes-microprofile-health', 'istio-intro'] //FIX Check with the team to see if this is still accurate, if not, gotta change the other cloud guides.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Deploying microservices on an OKD cluster 
:page-seo-description: A tutorial on how to deploy microservices on a containerized Red Hat OKD cluster or using a VM with Minishift. 
:guide-author: Open Liberty
= Deploying microservices on an OKD cluster

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].

Explore how to deploy microservices on a containerized Red Hat OKD 3.x cluster or using a VM with Minishift. 

//TODO What you'll learn
== What you'll learn 

You will learn how to quickly deploy a Red Hat OKD 3.x cluster on-premise using either a container or an all-in-one VM with Minishift. Then, you will deploy a simple REST microservice on an Open Liberty container to the running cluster.

OKD, formerly known as OpenShift Origin, is the upsteam open-source project that powers all OpenShift products. OKD is a Kubernetes-based platform with added functionality. It streamlines the DevOps process by providing an intuitive development pipeline. It also provides integration with multiple tools to make the deployment and management of cloud applications easier. To learn more about the different platforms that Red Hat OpenShift offers, check out their https://docs.openshift.com[official documentation^]. 

Kubernetes is an open source container orchestrator that automates many tasks that are involved in deploying, managing, and scaling containerized applications. If you would like to learn more about Kubernetes, check out the https://openliberty.io/guides/kubernetes-intro.html[Deploying microservices to Kubernetes^] guide.

Using Maven, you will build a simple microservice, called `system`, that collects basic system properties from your system and displays them on an endpoint that you can access in your web browser.

//TODO Additional Prerequisites
== Additional Prerequisites 

Before you begin, the following additional tools need to be installed:

- *Docker:* You need a containerization software for building containers that you will eventually deploy onto the OKD cluster. You will use Docker in this guide, for installation instructions, refer to the official https://docs.docker.com/install/[Docker documentation^].

//TODO Getting Started
== Getting Started